name: Sync Apple Docs

on:
  schedule:
    - cron: "0 7 * * *"   # daily 07:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Run sync
        run: bash scripts/sync_apple_docs.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(docs): sync Apple docs snapshots"
          title: "chore(docs): nightly Apple docs sync"
          body: |
            Updates local snapshots in `Docs/Apple/` from developer.apple.com.
            Source URLs: see `docs-config/apple_urls.txt`.
            Conversion: HTML → Markdown via pandoc.
          branch: chore/nightly-apple-docs-sync
          delete-branch: true
          labels: docs, automated
